import Head from 'next/head'
import Navbar from '../component/Navbar'
import TopContent from '../component/TopContent/TopContent'
import BlogContainer from '../component/BlogContainer/BlogContainer'
import Footer from '../component/Footer/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bdesh Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1 className='bg-warning'>Hello</h1> */}
      <div className='container-fluid shadow-sm nav-bg p-3'>
        <Navbar />
      </div>
      <div className='container-fluid b-dark p-3'>
        <TopContent />
      </div>
      <BlogContainer />
      <Footer />
    </div>
  )
}
